services:
    medicine_store:
        build: ./medicine_store
        image: medicine_store
        restart: always
        ports:
            - "8900:8900"
        volumes:
            - medicine_store_db:/data
            - /mnt/Data/medicine_tracker/logs/medicine_store:/logs/
        networks:
            - app_net

    daily_updater:
        build: ./daily_updater
        image: daily_updater
        restart: always
        volumes:
            - daily_updater_db:/data
            - /mnt/Data/medicine_tracker/logs/daily_updater:/logs/
        networks:
            - app_net
        depends_on:
            - medicine_store

    web:
        build: ./web
        image: web
        restart: always
        ports:
            - 9000:80
        networks:
            - app_net
        depends_on:
            - medicine_store
            - daily_updater

networks:
    app_net:

volumes:
    medicine_store_db:
    daily_updater_db:
